POST   http://localhost:3000/videos
Content-type: application/json


{
    "title": "Video teste 2",
    "description": "testando",
    "duration": 400
}

###

GET   http://localhost:3000/videos

###

PUT   http://localhost:3000/videos/f839fd7d-ae90-4949-80ab-a0af45bf2a94
Content-type: application/json


 {
    "title": "Vídeo teste part 2",
    "description": "Atualização do vídeo part 2",
    "duration": 400
 }

###

DELETE   http://localhost:3000/videos/e47ec1c6-feee-489c-8669-a4ca80a47e19




